- sampleProxy/24Solver/apiproxy/proxies/default.xml
- src/package/Endpoint.js
- src/package/plugins/unusedVariables.js
Can detect variables not used in flow steps; build symbol table from parts of flow including extractvariables (json and xml payload only at the moment).
TODO: 
1. parse javascript and determine what vars are used/set inside JS
2. other kinds of extract variables (e.g. query params etc)
> Partial implementation of unused vars

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/Policy.js
- lib/package/Resource.js
Currently, errors and warnings only increment the warningCount.
This corrects that and increments the appropriate property.
> hotfix: correct warning/error counts

- lib/package/Bundle.js
The Bundle.prototype.getEndpoints method uses Array.concat(), but does not assign the result.
Array.concat() does not affect the Array it is invoked on, but instead returns a new array. [See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat]
By assigning the result to the appropriate variable, target endpoints are returned in addition to the proxy endpoints.
> hotfix: correctly return all endpoints.

- lib/package/plugins/checkBundleStructure.js
> Fix issue where manifests folder not recognized as valid

- lib/package/plugins/checkBundleStructure.js
- package.json
Added `wsdl ` folder to the valid bundle structure
Fix #136
> Fix #135: wsdl folder is not recognized by plugin BN001

- lib/package/plugins/checkConditionLength.js
Just a simple typo I discovered whilst linting during my pipeline. I kept the casing intact, even though I think it would be more appropriate to either capitalize `Conditions` to match `Steps`, or instead keep `conditions` lowercase and also make `steps` lowercase to match.
> Fix typo in checkConditionLength

- lib/package/Endpoint.js
- lib/package/HTTPTargetConnection.js
Adding support for parsing HTTPTargetConnection. This allows code analysis of the URL and properties within the HTTPTargetConnection configuration. 
An example external plugin to use these new functions:
```
var plugin = {
ruleId: "CSTM001",
name: "Check if the HttpTargetConnection timeout is set",
message: "Timeout property should be set to 3 seconds or less in the HttpTargetConnection.",
fatal: false,
severity: 2, //error
nodeType: "Bundle",
enabled: true
};
var onTargetEndpoint = function(ep, cb) {
var httpTargetConnection = ep.getHTTPTargetConnection(),
hadError = false;
if (httpTargetConnection) {
var properties = httpTargetConnection.getProperties();
if (properties["connect.timeout.millis"] > 3000 || properties["connect.timeout.millis"] == null) {
ep.addMessage({
plugin,
message: …
```
> add support for HTTPTargetConnection

- README.md
- lib/package/plugins/checkBundleStructure.js
- the files ending in twiddle are backup files.
- also update README stating that ~ files are
ignored, as well as .DS_store.
> Ignore files like RF-Unauthorized.xml~

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/Policy.js
- lib/package/Resource.js
Currently, this change will make a difference only in the esLint plugin, which now allows people to configure severity for each of the various esLint rules. In the future, we can extend the jshint plugin to work the same way. Any future plugins can also benefit from this.
> prefer message item severity to plugin severity

- README.md
- lib/package/plugins/assignVariableUsage.js
- test/fixtures/resources/PO0026-assignVariable/apiproxy/PO0026-assignVariable.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-AssignVariable-MissingNameElement.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-AssignVariable-MultipleProblems.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-AssignVariable-RefWithCurlies.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-AssignVariable-TooManyNameElements.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/PO0026-assignVariable/apiproxy/proxies/endpoint1.xml
For issue #116  
This plugin checks for:
- exactly one Name element
- at most one Ref, at most one Template, at most one Value
- at least one of {Ref, Template, Value}
- if Ref, then the inner text should not be surrounded in curlies
Also update README and add a test.
> add PO026 to scan AssignVariable

- lib/package/Endpoint.js
- lib/package/plugins/mgmtServerTargetEndpointCheck.js
- lib/package/plugins/useTargetServers.js
This addresses issue #167 
Also, the plugins now use this method rather than performing xpath themselves.
> Endpoint.getName() now works correctly

- lib/package/plugins/bundleSizeResourceCount.js
- lib/package/plugins/checkForMultipleStatsCollectorPolicies.js
- lib/package/plugins/distributedQuotaCheck.js
- lib/package/plugins/emptyRouteRuleLast.js
- lib/package/plugins/emptyRouteRules.js
- lib/package/plugins/eslint.js
- lib/package/plugins/extractFormParamConditionCheck.js
- lib/package/plugins/extractJSONConditionCheck.js
- lib/package/plugins/extractXMLConditionCheck.js
- lib/package/plugins/jsHint.js
- lib/package/plugins/mgmtServerTargetEndpointCheck.js
- lib/package/plugins/policyCount.js
- lib/package/plugins/quotaPolicyReuseCheck.js
- lib/package/plugins/responseCacheErrorResponseCheck.js
- lib/package/plugins/serviceCalloutRequestName.js
- lib/package/plugins/serviceCalloutResponseName.js
- lib/package/plugins/threatProtectionJSONConditionCheck.js
- lib/package/plugins/threatProtectionXMLConditionCheck.js
- lib/package/plugins/unusedVariables.js
- lib/package/plugins/useTargetServers.js
Eg, enable debugging for eslint plugin via
`DEBUG=bundlelinter:PO025 node ./cli.js ...`
Previously the debug used the "name" property on the plugin which included whitespace, not the appropriate thing to use in a debug flag.
> debug for all plugins now uses the plugin ruleId

- lib/package/plugins/jsHint.js
This uses the jshint cli function to find the rc file to apply, searching up the directory hierarchy.  If none is found, then the plugin uses the default options, { maxerr: 50 } .
It also reformats the error message slightly from previously; not all "errors" in the return from JSHINT are actually errors. Some are warnings. The new logic treats them as such.
> jshint plugin now finds and reads a .jshintrc file

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/FaultRule.js
- lib/package/Flow.js
- lib/package/FlowPhase.js
- lib/package/Step.js
- lib/package/bundleLinter.js
- lib/package/myUtil.js
- package.json
Using async.parallel may provide small perf advantages, but because there is no I/O or waiting, it's probably negligible. But async.parallel has costs - for example any exception thrown by a plugin will get swallowed. Also the code that uses the async module is less readable, too.
Therefore, let's remove unnecessary parallelism.
> remove unnecessary parallelism

- README.md
- lib/package/Endpoint.js
- lib/package/plugins/proxyNameAttr.js
- lib/package/plugins/targetNameAttr.js
name attribute should match the filename for the ProxyEndpoint or TargetEndpoint. This is now enforced during upload by ngsaas.
> add check for {Proxy,Target}Endpoint on name

- README.md
BN004 is not enabled, currently. It appears that the module is a work-in-progress, and was never "enabled". Therefore the checks within that plugin never run. This change updates the README to reflect that.
This is related to #192.  We should address #192, but that will take some time. In the meantime, we should update the README.
> update README to correctly reflect status of BN004

- lib/package/plugins/assignVariableUsage.js
This is a change interesting only to developers and maintainers of the assignvariable plugin.
> use the correct value for debug in assignvar plugin

- cli.js
- lib/package/bundleLinter.js
A new parameter "--maxWarnings" (inspired by ESLint) has been added.
If more warnings are reported than allowed, the lint will exit with an error code - allowing CI/CD pipelines to fail on bad quality commits.
The default value for --maxWarnings is -1, which disables this new feature.
This solves issue #214
> Allow apigeelint to fail, if maximum number of warnings is exceeded

- lib/package/bundleLinter.js
- test/specs/stepHygiene.js
- this change adds a config option, setExitCode which when present and false, disables process.exit() in the case where there are errors or the number of warnings exceeds the configured maximum. 
- also add tests for step hygiene (ST002), which exercises this option.
> allow config setExitCode to disable process.exit()

- README.md
- lib/package/plugins/PO013-jsHint.js
The plugin now searches "up" the directory tree for a .jshintignore file, and ignores files noted within it.
> PO013 support .jshintignore files

- lib/package/plugins/BN001-checkBundleStructure.js
this is to support new archetypes supported in apigee x/hybrid including oas and properties resource files
> add support for oas and properties in bundle (BN001) plugin

- lib/package/plugins/CC005-unterminatedStrings.js
This fixes an exception that occurs with a condition like:
`<Condition>(message.status.code &gt;= 500)</Condition>`
> CC005 coerce param to string before testing

- lib/package/plugins/PO026-assignVariableUsage.js
- test/fixtures/resources/PO026-assignVariable-resourceUrl/AM-AssignVariable-1.xml
- test/specs/profile.js
There is a new syntax for AssignVariable, allowing `ResourceURL` as a source for the value.  It looks like this:
```
<AssignMessage name='AM-Value-From-ResourceURL'>
<AssignVariable> 
<Name>variable-to-set</Name> 
<ResourceURL>xsl://name-of-stylesheet.xsl</ResourceURL> 
</AssignVariable> 
</AssignMessage>
```
This change introduces handling for that element in the PO026 plugin. 
Also adds a new test for same, for 2 profiles.
> add ResourceURL to PO026 plugin

- README.md
- lib/package/plugins/DC001-deprecationConcurrentRateLimit.js
- lib/package/plugins/DC002-deprecationOAuthV1.js
- test/fixtures/resources/DC001-concurrentratelimit-deprecation/apiproxy/Products-API.xml
- test/fixtures/resources/DC001-concurrentratelimit-deprecation/apiproxy/policies/ConnectionThrottler.xml
- test/fixtures/resources/DC001-concurrentratelimit-deprecation/apiproxy/proxies/default.xml
- test/fixtures/resources/DC001-concurrentratelimit-deprecation/apiproxy/targets/default.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/Products-API.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/policies/Delete-OAuth-v10-Info-1.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/policies/Get-OAuth-v10a-Info-1.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/policies/OAuth-v10a-1.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/proxies/default.xml
- test/fixtures/resources/DC002-deprecation-oauthv1/apiproxy/targets/default.xml
- test/specs/testDeprecationConcurretRatePolicy.js
- test/specs/testDeprecationOAuthv1.js
Add a new category of warnings to cover deprecated features 
- DC001 - ConcurrentRateLimit policy
- DC002 - 3 - OAuthV1 policies
> deprecation warnings for ConcurrentRateLimit, OAuthV1 policies

- package.json
Chalk latest is installed but is unsupported by this repo - advise setting to 4.1.2 until app can be modified to support Chalk latest.
> Set chalk version to last compatible

- README.md
- lib/package/plugins/PO031-assignMessage-ContentType.js
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/fail/AM-Missing-ContentType.xml
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/fail/AM-RedundantHeader.xml
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/fail/AM-RedundantPayload.xml
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/fail/messages.js
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/pass/AM-ContentTypeAttribute.xml
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/pass/AM-NoPayload.xml
- test/fixtures/resources/PO031-AssignMessage-Payload-ContentType/pass/AM-SetHeader.xml
- test/specs/PO031-AssignMessage-Payload-ContentType.js
Assign a content-type if assigning a Payload.
Must not redundantly assign a content-type.
Also, an update to the README for this feature.
> PO031 new plugin to check Set/Payload in AssignMessage

- README.md
Add links to best practices and anti-patterns for solving this issue: https://github.com/apigee/apigeelint/issues/121
> Add links to best practices and anti-patterns

- lib/package/plugins/PO001-threatProtectionJSONConditionCheck.js
- lib/package/plugins/PO003-extractJSONConditionCheck.js
- lib/package/plugins/PO004-extractXMLConditionCheck.js
- lib/package/plugins/_extractVariablesCheck.js
- test/specs/PO004-ExtractXML-ConditionCheck.js
This change resolves #296 
The prior tests were checking only known message variables.
The ExtractVariables policy can also be used on arbitrary strings. The new checks consider that. Same consideration for PO004, which applies to XMLPayload.
This is a correction of an existing function, not a new capability. No change to readme is required.
Before merging it would be good to get confirmation from the original reporter.
> rework checks on Conditions for PO003 and PO004

- README.md
- lib/package/plugins/BN001-checkBundleStructure.js
- lib/package/plugins/BN006-policyCount.js
- lib/package/plugins/BN010-missingPolicies.js
- test/fixtures/resources/BN010-missing-policy/apiproxy/BN010-missing-policies.xml
- test/fixtures/resources/BN010-missing-policy/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/BN010-missing-policy/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/BN010-missing-policy/apiproxy/policies/JS-1.xml
- test/fixtures/resources/BN010-missing-policy/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/BN010-missing-policy/apiproxy/proxies/endpoint1.xml
- test/specs/BN010-1.js
new BN010 plugin checks for policies that are referenced in the bundle, but not present.
> new BN010 plugin to check for Missing policies

- lib/package/plugins/PO018-checkRegexLookAround.js
- test/specs/PO018-checkRegexLookAround.js
The test for regexp lookarounds in PO0018 simply checks whether the string `(?` is present in the `<Pattern>` tag, without taking into account that the regexp might contain `(?i)` in order to flag it as case-insensitive. This change alters the condition to allow for that exception, ironically by using a negative lookahead to check whether the `(?` is followed by `i)`.
> Don't flag case-insensitive regex as lookaround in PO0018

- README.md
- lib/package/bundleLinter.js
- lib/package/plugins/PO032-CORS-hygiene.js
- test/fixtures/resources/PO032/fail/AllowCredentials-Duplicated.xml
- test/fixtures/resources/PO032/fail/AllowCredentials-invalid-value.xml
- test/fixtures/resources/PO032/fail/AllowCredentials-missing-value.xml
- test/fixtures/resources/PO032/fail/AllowHeaders-Duplicated.xml
- test/fixtures/resources/PO032/fail/AllowHeaders-Misformatted.xml
- test/fixtures/resources/PO032/fail/AllowMethods-Duplicated.xml
- test/fixtures/resources/PO032/fail/AllowMethods-Misformatted.xml
- test/fixtures/resources/PO032/fail/AllowMethods-missing-value.xml
- test/fixtures/resources/PO032/fail/AllowOrigin-Multiple-with-Wildcard.xml
- test/fixtures/resources/PO032/fail/AllowOrigin-Origin-ends-with-slash.xml
- test/fixtures/resources/PO032/fail/AllowOrigin-Wildcard.xml
- test/fixtures/resources/PO032/fail/AllowOrigin-request-header-origin.xml
- test/fixtures/resources/PO032/fail/ExposeHeaders-Dupe.xml
- test/fixtures/resources/PO032/fail/messages.js
- test/fixtures/resources/PO032/pass/CORS-1.xml
- test/fixtures/resources/PO032/pass/CORS-Multiple-Origins.xml
- test/specs/PO032-CORS-hygiene-test.js
This is a new plugin, to check the hygiene of the CORS policy. 
errors:
- for any origins that end in slash
- for elements that are duplicated
- for values that are misformatted
warnings:
- use wildcard for AllowOrigins
- use {request.header.origin} for AllowOrigins
- if AllowOrigins does not exist
The warning for "wildcard for AllowOrigins" may trigger often, especially for proxies in development.
> new plugin for CORS policy hygiene

- lib/package/Endpoint.js
- lib/package/plugins/EP002-misplacedElements.js
Fix for 331
- For Apigee Edge, with HostedTarget, the HTTPTargetConnection becomes optional in the TargetEndpoint
- Added checks in the EP002 plugin to check for 'LocalTargetConnection', 'HTTPTargetConnection', 'HostedTarget' if the profile is Apigee
> Fix for #331

- lib/package/plugins/PO026-assignVariableUsage.js
- lib/package/plugins/_pluginUtil.js
- package-lock.json
- test/fixtures/resources/PO026-apigeex-proxy/apiproxy/policies/AM-config-properties.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-1.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-2.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-3.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-4.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-5.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-6.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-7.xml
- test/fixtures/resources/PO026-assignVariable-policies/PropertySetRef-8.xml
- test/fixtures/resources/PO026-assignVariable-policies/ResourceUrl.xml
- test/specs/BN001-xsdResourceTest.js
- test/specs/PO026-assignVariableHygiene.js
- test/specs/PO026-profile.js
- test/specs/testTemplateCheck.js
This change removes the check for curlies in AssignVariable/PropertySetRef.
> fix: allow curlies in PropertySetRef

- lib/package/plugins/PO026-assignVariableUsage.js
- lib/package/plugins/_pluginUtil.js
- test/fixtures/resources/PO026-assignVariable-policies/Template-1.xml
- test/fixtures/resources/PO026-assignVariable-policies/Template-2.xml
- test/specs/PO026-profile.js
- test/specs/testTemplateCheck.js
The change for #383 works for PropertySetRef, but it is not general for "any message template".  
This change extends the check for validity of templates to any message template. 
also, new tests for this case.
The validity check can now be used for future plugins that check, for example, any template or string inside a Payload or etc.
> Json template check

- lib/package/plugins/PO026-assignVariableUsage.js
- lib/package/plugins/_pluginUtil.js
- test/fixtures/resources/PO026-assignVariable-policies/Template-1.xml
- test/specs/PO026-profile.js
- test/specs/testTemplateCheck.js
This corrects #387 .
Also, run prettier on affected .js files.
> Allow spaces in template function arguments

- README.md
- lib/package/plugins/FE001-authentication.js
- test/fixtures/resources/FE001-Authentication/apiproxy/flightdata.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-Clean-Response-Headers.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-PreparedQuery-1.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-PreparedQuery-2.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-PreparedQuery-3.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-PreparedQuery-4.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/AM-Query.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/EC-1-valid.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/EC-2-accesstoken.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/EV-PathParams-4.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/JS-Convert-Response.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/SC-1-valid.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/policies/SC-2-multiple-token-nodes.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/targets/target-1.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/targets/target-2.xml
- test/fixtures/resources/FE001-Authentication/apiproxy/targets/target-3.xml
- test/specs/FE001-Authentication-element.js
add a new plugin to check the use of the Authentication element in ServiceCallout, ExternalCallout, and TargetEndpoint. Because this check looks at two distinct policies and an endpoint, it didn't fit into any of the existing plugin categories.  Rather than breaking it into 3 new plugins, one for each policy and one for the targetendpoint, I added a new "feature" plugin type, and created this plugin (FE001) as the first of its type. It checks for this feature in all three places.
> feat(plugin): FE001 plugin to check use of Authentication element

- lib/package/Condition.js
- lib/package/plugins/CC001-checkConditionForLiterals.js
- test/specs/CC001-CheckConditionForLiterals.js
With this change, the CC001 now correctly parses a Condition string that occupies multiple lines. Previously, that plugin could flag the Condition as containing a string literal.
> fix(CC001): correct parsing of multiline Conditions

- lib/package/plugins/PO033-extractVariables-hygiene.js
- test/fixtures/resources/PO033/fail/EV-URIPath-with-lowercase-pattern-element.xml
- test/fixtures/resources/PO033/fail/EV-Variable-with-no-Pattern.xml
- test/fixtures/resources/PO033/fail/messages.js
- test/fixtures/resources/PO033/pass/EV-URIPath-with-Pattern-element.xml
- test/specs/PO033-extractVariables-JSON-Variable-type.js
With this change, PO033 checks for the presence of at least one Pattern element under QueryParam, FormParam, Header, Variable, and URIPath. And also checks there are no elements of other names.
It is not necessary to change the README with this enhancement, as the existing description of PO033 remains accurate.
> feat(PO033): add new checks for valid elements in PO033 plugin

- lib/package/Bundle.js
- test/fixtures/resources/newBundle/apiproxy/proxies/default.xml
- test/specs/testBundle.js
External plugins were unable to add messages to the report if there wasn't a root xml for the proxy/shared flow, as reported in #409. This PR fixes that issue.
> Fixes issue with "undefined" proxies

- package.json
The postinstall script was attempting to invoke peggy from the node_modules folder directly. This works fine when manually running the postinstall script from the apigeelint repo, but fails when the package is being installed from npm.
I changed the invocation from invoking peggy directly to using `npx`.
Solves issue #407
> changes how peggy is invoked on postinstall

- NOTICE
- README.md
- lib/package/Endpoint.js
- lib/package/Flow.js
- lib/package/Policy.js
- lib/package/myUtil.js
- lib/package/plugins/PO019-serviceCalloutRequestName.js
- package-lock.json
- package.json
In some cases, the tool called xpath.select() with an object that was not a DOM element. With v0.0.33 of the xpath module, the error was silently ignored. But with v0.0.34 of the xpath module, this caused an error message like so: 
```
Error: Context node does not appear to be a valid DOM node.
at XPath.evaluate (/Users/dchiesa/dev/apigeelint/node_modules/xpath/xpath.js:1359:19)
at XPathExpression.evaluate (/Users/dchiesa/dev/apigeelint/node_modules/xpath/xpath.js:4536:33)
at exports.selectWithResolver (/Users/dchiesa/dev/apigeelint/node_modules/xpath/xpath.js:4989:33)
at exports.select (/Users/dchiesa/dev/apigeelint/node_modules/xpath/xpath.js:4969:24)
at FlowPhase.getSteps (/Users/dchiesa/dev/apigeelint/lib/package/FlowPhase.js:50:21)
at …
```
> fix: do not call xpath.select() with non element

- build/ConditionParser.js
- lib/peggy/Apigee-Condition.pegjs
- test/specs/ConditionParserTest.js
Modify the peggyjs grammar to allow variables on the right hand side of SOME operators. 
Add tests to verify that behavior.
This should address #410.
> fix: in peggyjs, allow variable on RHS of some operators

- cli.js
Very small change. This avoids a runtime error when the option is missing.
> fix: check for path, if the list option is not passed

- build/ConditionParser.js
- lib/peggy/Apigee-Condition.pegjs
- test/specs/ConditionParserTest.js
The checks for Is and IsNot were in the incorrect order. This change corrects that. 
And adds tests for same. This addresses #422 .
> fix: re-order checks for Is and IsNot

- README.md
- lib/package/third_party/formatters/codeclimate.js
Linked to issue : https://github.com/apigee/apigeelint/issues/427
To use full functionnalities on GitLab CI/CD, it would be nice to implement codeclimate formatter to use codequality reports artifact into pipeline job artifacts as bellow: 
```yml
apigeelint:
stage: lint
image: node:12-alpine
before_script:
- npm install -g apigeelint
script:
- apigeelint -f codeclimate.js > apigeelint-results.json
artifacts:
reports:
codequality:
- "${CI_PROJECT_DIR}/apigeelint-results.json"
```
Code Quality of GitLab use CodeClimate json format, with enforcement on fingerprint which is not optional for GitLab CI/CD.
Codequality : https://docs.gitlab.com/ee/ci/testing/code_quality.html
Codeclimate specification : https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types
> [DevOps] Add CodeClimate style fomatter to use apigee-lint into GitLab CI/CD

- README.md
- lib/package/plugins/BN012-unreferencedTargets.js
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/proxies/endpoint2.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/targets/target-1.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/targets/target-2.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/targets/target-3.xml
- test/fixtures/resources/BN012-unreferenced-target/apiproxy/unreferenced-target.xml
- test/specs/BN012-unreferenced-targets.js
I was surprised to see that apigeelint did not flag unreferenced TargetEndpoints. 
This new plugin fills that gap.
> feat: BN012 plugin to find unreferenced targets

- lib/package/plugins/PD003-emptyRouteRuleLast.js
- test/specs/PD003-conditions-on-RouteRules.js
The error message for PD003 is unclear and confusing. Before this change, it reads: 
```
Endpoint has an unconditional RouteRule that is not the final RouteRule. It will be ignored.
```
It is not clear what "It" refers to, in "It will be ignored."  By convention in English, "It" to begin a sentence normally refers to the subject of the prior sentence. But here, "It" refers to the final RouteRule. So that's confusing. 
The message is clearer when stated more simply: 
```
Endpoint has an unconditional RouteRule that is not the final RouteRule.
```
Accompanying this change, there's some cleanup of commented blocks of code, and formatting changes via `prettier` .
> fix: correct PD003 error message

- lib/package/Policy.js
- lib/package/plugins/PO012-assignMessageAssignTo.js
- lib/package/plugins/PO034-am-hygiene.js
- test/fixtures/resources/PO012-assignToHygiene/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/PO012-assignToHygiene/apiproxy/policies/AM-Modify-Request-Remove-ApiKey.xml
- test/fixtures/resources/PO012-assignToHygiene/apiproxy/proxies/default.xml
- test/specs/PO012-assignToHygiene.js
The PO012 plugin previously would silently choke when some of the attributes on the AssignTo element were missing. 
This change fixes that.  And adds some new tests to support that.
> fix: PO012 (AssignTo hygiene) now handles missing attributes

- README.md
- cli.js
- lib/package/apigeelintrc.js
This change adds support for reading program options from an .apigeelintrc file. 
And, there is a new option, `--norc` , which tells apigee to not look for an `.apigeelintrc` file. 
Beyond that, no functional changes. 
Also updated the README. 
Please review before merge!
> feat: .apigeelintrc file

- lib/package/plugins/PD002-emptyRouteRules.js
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/failed-route.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/policies/AM-Clean-Request-Headers-From-Response.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/PD002-no-unconditional-routerule/apiproxy/targets/target-1.xml
- test/specs/PD002-at-least-one-unconditional-RouteRule.js
Alter plugin PD002 to now check for zero unconditional RouteRules. 
Without this change PD002 checks for _more than one_ unconditional RouteRule. But it does not check for _exactly one_.  With zero unconditional RouteRules, at runtime the proxy can generate this error: 
```
{
"fault": {
"faultstring": "Unable to route the message to a Target Endpoint",
"detail": {
"errorcode": "messaging.runtime.RouteFailed"
}
}
}
```
This change ALSO modifies PD002 to flag the _redundant_ RouteRules when there are multiple. Previously it flagged every unconditional RouteRule (1..n); now it flags only 2..n.
> fix: PD002 checks for zero unconditional RouteRules

- lib/package/plugins/PO035-quota-hygiene.js
- test/fixtures/resources/PO035/policies/fail/Asynch-neither-child-element.xml
- test/fixtures/resources/PO035/policies/fail/messages.js
- test/fixtures/resources/PO035/policies/pass/Asynch-both-elements.xml
Contrary to the (current) documentation the `AsynchronousConfiguration` element within the Quota policy allows the use of both `SyncIntervalInSeconds` and  `SyncMessageCount`, in the same configuration.  This is valid: 
```
<Quota name="Q-Asynch">
. . . 
<AsynchronousConfiguration>
<SyncIntervalInSeconds>20</SyncIntervalInSeconds>
<SyncMessageCount>5</SyncMessageCount>
</AsynchronousConfiguration>
</Quota>
```
This change modifies the PO035 plugin to allow that.
> fix: PO035 allows both of Sync{IntervalInSeconds, MessageCount}

- cli.js
- lib/package/apigeelintrc.js
No functional changes. Just debug statements that will help identify which rc file  apigeelint loads. 
Usage
```
DEBUG=apigeelint:rc node cli.js ...
```
> chore: add debug messages for apigeelint rc file

- README.md
- cli.js
- lib/package/Bundle.js
- lib/package/myUtil.js
- lib/package/plugins/BN012-unreferencedTargets.js
- lib/package/plugins/TD002-useTargetServers.js
- lib/package/plugins/TD007-targetSslInfo-Truststore.js
- package-lock.json
- package.json
- test/fixtures/resources/disable-directives/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/disable-directives/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/disable-directives/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/disable-directives/apiproxy/proxies/endpoint2.xml
- test/fixtures/resources/disable-directives/apiproxy/targets/target-1.xml
- test/fixtures/resources/disable-directives/apiproxy/targets/target-2.xml
- test/fixtures/resources/disable-directives/apiproxy/targets/target-3.xml
- test/fixtures/resources/disable-directives/apiproxy/targets/target-4.xml
- test/fixtures/resources/disable-directives/apiproxy/unreferenced-target.xml
- test/specs/BN012-unreferenced-targets.js
- test/specs/TD007-target-sslInfo-truststore.js
- test/specs/disable-directives.js
This addresses #444 .
It allows suppressing errors or warnings, generated on a particular file, with the inclusion of a comment in the specific XML file. The comment should look like this: 
```xml
```
It needs to appear on the line before the line that would be mentioned in the error or warning. 
Also: 
- updated TD002 to use the correct line number in the warnings, so that they can be properly disabled.
- updated BN012 to use the correct module in the error message. 
- updated BN012 test to be more robust. 
- added a command-line switch to disable this feature.
- added tests for this feature as well as the command-line switch.
- updated README describing this feature.
> feat: allow disable directives within the XML configuration

- lib/package/myUtil.js
apigeelint uses get-installed-path to get the path of xmldom/xmldom , in order to read the constants that are exported in the v0.8.x version of that package.  Later versions of the package export the constants, but they're not yet released. 
ANYWAY, the get-installed-path looks in the wrong place if you run apigeelint from a directory that is not its home, and that causes the apigeelint cli to just throw an error and exit. This change fixes that.
> fix: get-installed-path needs direction on where to look

- README.md
- lib/package/plugins/PO036-serviceCallout-response-element.js
- test/fixtures/resources/PO036/SC-Response-element-invalid1.xml
- test/fixtures/resources/PO036/SC-Response-element-invalid2.xml
- test/fixtures/resources/PO036/SC-Response-element-invalid3.xml
- test/fixtures/resources/PO036/SC-Response-element-invalid4.xml
- test/fixtures/resources/PO036/SC-Response-element-invalid5.xml
- test/fixtures/resources/PO036/SC-Response-element-invalid6.xml
- test/fixtures/resources/PO036/SC-Response-element-valid.xml
- test/specs/PO036-service-callout-response-element-syntax.js
This plugin checks the usage of the `Response` element in the ServiceCallout policy. 
It rejects these , for example: 
```
<Response variable='jwksResponse'/> 
<Response attr='something'>text_value</Response> 
<Response/> 
<Response>  </Response> 
<Response>not a valid variable name</Response> 
```
And it also flags repeated `Response` elements.
> feat: PO036 check usage of Response element in ServiceCallout

- README.md
- lib/package/plugins/BN014-duplicate-policies.js
- lib/package/plugins/EP001-corsPolicyAttachment.js
- test/fixtures/resources/BN014/cors-test/README.md
- test/fixtures/resources/BN014/cors-test/apiproxy/cors-test.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/AM-Clean-Request-Headers-From-Response.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/AM-Response-2.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/AM-Response-3.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/CORS-1.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/CORS-A.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/policies/VerifyAPIKey-1.xml
- test/fixtures/resources/BN014/cors-test/apiproxy/proxies/endpoint1.xml
- test/specs/BN014-duplicate-policies.js
- test/specs/PO037-DataCapture-hygiene.js
I don't know why, but previously the EP001 plugin, which is intended to check for CORS policy placement, also made a lame attempt to check for duplicate CORS policies. That *always* failed, because the check was naive: any policy that had a different name was considered to be different. Therefore it never detected a duplicate.
So that code needed to go.  But it seems like it's _possible_ that someone might have multiple differently named policies (CORS or otherwise), with identical configuration, in the same proxy bundle. And if that might occur, it would be good to check for that and issue a warning. So I implemented that check in a new plugin, BN014. It has "pretty good" XML policy comparison logic: two different policies will not be judged to be different if the only differences are in …
> feat: BN014 detect duplicate policies

- README.md
- lib/package/plugins/TD008-target-LB-duplicate-servers.js
- lib/package/plugins/TD008-target-LB-servers.js
- lib/package/plugins/TD009-target-LB-multiple-LB.js
- test/fixtures/resources/TD008/fail/t1.xml
- test/fixtures/resources/TD008/fail/t2.xml
- test/fixtures/resources/TD008/fail/t3.xml
- test/fixtures/resources/TD008/fail/t4.xml
- test/fixtures/resources/TD008/fail/t5.xml
- test/fixtures/resources/TD008/pass/t1.xml
- test/fixtures/resources/TD008/pass/t2.xml
- test/fixtures/resources/TD008/pass/t3.xml
- test/fixtures/resources/TD008/pass/t4.xml
- test/fixtures/resources/TD009/fail/t1.xml
- test/fixtures/resources/TD009/pass/t1.xml
- test/fixtures/resources/TD009/pass/t2.xml
- test/specs/TD008-test.js
- test/specs/TD009-test.js
New Plugins TD008 and TD009.  
TD008 addresses #469 and #470 .  It checks for duplicate server entries, or cases in which there are multiple IsFallback entries. Or, when there is no `name=` attribute on the Server entry. 
TD009 checks for multiple LoadBalancers. 
Updated README.
> feat: TD008 and TD009 to perform checks on LoadBalancer

- README.md
- lib/package/plugins/PO038-kvm-mapname.js
- test/fixtures/resources/PO038/fail/KVM-MapName-apigee.xml
- test/fixtures/resources/PO038/fail/KVM-both-MapName-and-mapIdentifier-apigee.xml
- test/fixtures/resources/PO038/fail/KVM-both-MapName-and-mapIdentifier-apigeex.xml
- test/fixtures/resources/PO038/fail/KVM-empty-MapName-apigeex.xml
- test/fixtures/resources/PO038/fail/KVM-missing-mapIdentifier-apigee.xml
- test/fixtures/resources/PO038/fail/KVM-neither-MapName-nor-mapIdentifier-apigeex.xml
- test/fixtures/resources/PO038/fail/messages.js
- test/fixtures/resources/PO038/pass/KVM-MapName-apigeex.xml
- test/fixtures/resources/PO038/pass/KVM-just-mapIdentifier-apigee.xml
- test/fixtures/resources/PO038/pass/KVM-just-mapIdentifier-apigeex.xml
- test/specs/PO038-test.js
Add a new plugin to check KeyValueMapOperations policy
- in apigeex profile, t must use either MapName or mapIdentifier, not both
- in apigee profile, it must use mapIdentifier, and not MapName
> feat: PO038 check KeyValueMapOperations MapName and identifier

- README.md
- lib/package/plugins/TD016-healthmon-but-no-loadbalancer.js
- test/fixtures/resources/TD016/fail/t1-no-LoadBalancer-but-with-HealthMonitor.xml
- test/fixtures/resources/TD016/pass/t1-with-LoadBalancer-and-HealthMonitor.xml
- test/fixtures/resources/TD016/pass/t2-with-LoadBalancer-and-no-HealthMonitor.xml
- test/fixtures/resources/TD016/pass/t3-no-LoadBalancer-no-HealthMonitor.xml
- test/specs/TD016-test.js
> feat: TD016 check that HealthMonitor present only when applicable

- README.md
- lib/package/plugins/PO039-messageLogging-responseType.js
- test/fixtures/resources/PO039/ML-test-invalid1.xml
- test/fixtures/resources/PO039/ML-test-invalid2.xml
- test/fixtures/resources/PO039/ML-test-invalid3.xml
- test/fixtures/resources/PO039/ML-test-valid1.xml
- test/fixtures/resources/PO039/ML-test-valid2.xml
- test/fixtures/resources/PO039/ML-test-valid3.xml
- test/specs/PO039-test.js
The ResourceType element in the MessageLogging policy underCloudLogging, should either be blank (the default) or should specify "api".  
This plugin checks that and issues a warning.  It also checks other hygiene associated to CloudLogging and issues warnings or errors in those cases.
> feat: P039 to scan MessageLogging/CloudLogging

- README.md
- lib/package/Endpoint.js
- lib/package/Flow.js
- lib/package/plugins/ST008-unreachable-policies-after-raisefault.js
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/AM-Extra-Header.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/JS-RemoveCopiedHeaders.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/RF-Error-Not-Enabled.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/RF-Error.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/policies/RF-Invalid-Request.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/proxies/endpoint2.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/apiproxy/unreached-policies.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/sharedflowbundle/Shared-Flow-1.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/sharedflowbundle/policies/AM-Header-1.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/sharedflowbundle/policies/AM-Header-2.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/sharedflowbundle/policies/RF-Unsupported.xml
- test/fixtures/resources/ST008-unreached-policies-after-raisefault/sharedflowbundle/sharedflows/sf-default.xml
- test/specs/ST008-test.js
This new plugin checks for policies that are attached after a RaiseFault , in any sequence.
> feat: ST008 check for policies attached after RaiseFault

- test/specs/PO039-test.js
This is a one-line fix for tests for PO039.
> fix: correct errant tests for PO039

- README.md
This fixes #494. 
Doc update only.
> docs: clarify the requirement for naming of External Plugins

- NOTICE
- README.md
- cli.js
- lib/package/downloader.js
- package-lock.json
- package.json
Now the CLI download argument can accept segments like this: 
- `rev:N` - specify a particular revision of a sharedflow or apiproxy to download
- `env:ENVNAME` - an environment; apigeelint will download the latest revision of the named sharedflow or apiproxy that is deployed to this environment
> enable the Downloader to accept a revision or environment

- README.md
- cli.js
- lib/package/downloader.js
This is just a simplification of the parsing logic for the download option.
And a few touchups on messages emitted in error cases - incorrect arguments passed, and so on.
This PR does not change the behavior of apigeelint, other than rewording of error messages.
> Simplify download logic

- package.json
This is an internal development feature, adding the depcheck tool to the run scripts.
No new user-accessible features.
> feat: add depcheck as a run script

- lib/package/TruthTable.js
- test/specs/testTruthTable.js
This fix adds proper handling of null in TruthTable, to allow expressions like 
`geocodingResponse.content != null`
> fix: correct handling of null in Conditions within TruthTable

- lib/package/plugins/TD012-targetSslInfo-exactly-one-SSLInfo.js
- test/fixtures/resources/TD012/fail/messages.js
- test/specs/TD012-test.js
change TD012 warning message, when a LoadBalancer is in use, to 
```
"TargetEndpoint HTTPTargetConnection is missing SSLInfo configuration"
```
> fix: adjust TD012 warning messages, and test for same

- lib/package/plugins/PO026-assignVariableUsage.js
- lib/package/plugins/_pluginUtil.js
- test/fixtures/resources/PO026-assignVariable/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/PO026-assignVariable/apiproxy/policies/AM-JsonPath-1.xml
- test/fixtures/resources/PO026-assignVariable/apiproxy/proxies/endpoint1.xml
- test/specs/PO026-assignVariableHygiene.js
- test/specs/testTemplateCheck.js
AssignMessage with this: 
```
<AssignVariable>
<Name>selected_value</Name>
<Template>{jsonPath('$.quota.[*].appname',jsondata)}</Template>
</AssignVariable>
```
...can trigger an unwarranted warning from PO026.  This change corrects that, and adds a few tests.
> fix: validateTemplate adjustment for quoted jsonPath expressions

- lib/package/plugins/TD004-targetSslInfo-enabled-and-enforce.js
- test/specs/TD004-test-sslInfo.js
This small fix tweaks the TD004 plugin to allow a variable/template in the URL for HTTPTargetConnection .
> fix: correct check in TD004 to allow for variable in URL
