apigee/apigeelint

- lib/package/bundleLinter.js
> Exit code should return 1 when there are errors

- lib/package/plugins/checkForMultipleStatsCollectorPolicies.js
> Ammend ruleId and nodeType in Statistics Collector - duplicate policies

- cli.js
-V should return currect version
Fixed #99
> Fix version command

- lib/package/plugins/checkBundleStructure.js
> BN001: Add openapi folder to Bundle folder structure

- lib/package/plugins/checkBundleStructure.js
Added Hosted Targets to bundle structure `BN001`
Close #111
> Add hosted target support

- cli.js
- lib/package/bundleLinter.js
This is the code to pass an exclude parameter to exclude a list of rules; addresses issue #127 
ex: apigeelint -s apiproxy -f table.js -e PO006,PO008
> Exclude parameter

- lib/package/Endpoint.js
Hi Team,
I am creating this pull request to have support for post client flow in apigee linting. Right now in existing implementation it is giving me warning that my policy is not attached, although it is attached in postclient flow.
Thanks
> adding changes for postclient flow

- lib/package/Bundle.js
- lib/package/plugins/checkBundleStructure.js
Follow up for #133 
BN001 should ignore `node_modules` folder as well
> BN001 should ignore node_modules folder

- lib/package/plugins/checkBundleStructure.js
> BN001: Added XML extensions under resources/node folder

- README.md
- cli.js
- lib/package/Bundle.js
- lib/package/BundleTypes.js
- lib/package/Endpoint.js
- lib/package/Flow.js
- lib/package/plugins/checkBundleStructure.js
- lib/package/plugins/eslint.js
- package.json
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/TwentyFour.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/AssignMessagebadDisplayName.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractParamVariables.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractPayloadVariables.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractVariables.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractVariablesFault.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractVariables_1.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/ExtractVariables_unattached.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/JSONThreatProtection.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/badServiceCallout.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/jsCalculate.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/lookup.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/regEx.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/regExLookAround.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/policies/statColl.xml
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/resources/jsc/jsCalculate.js
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/resources/jsc/jsCalculate.jsfoo
- test/fixtures/resources/sampleFlow/24Solver/sharedflowbundle/sharedflows/default.xml
- test/specs/testAllPlugins.js
- test/specs/testesLint.js
Adding SharedFlow Bundle Support, fixing exclude options bug and adding EsLinter for js resources as rule PO025
> SharedFlow Bundle Support, EsLinter support, bug fix

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/Flow.js
- lib/package/Policy.js
- test/specs/testUnattachedPolicies.js
Fixes false warnings that policies are missing from steps in sharedflow bundles.
> Issue 151 Fix false warnings for shared flows

- README.md
- lib/package/Bundle.js
- lib/package/plugins/policyNameConventions.js
- lib/package/plugins/useTargetServers.js
- test/fixtures/resources/sampleProxy/24Solver/apiproxy/policies/KV-config-values.xml
- test/fixtures/resources/sampleProxy/24Solver/apiproxy/proxies/default.xml
Issue #158  Endpoint rules are not reporting results
Issue #159 KeyValueMapOperations should allow for KV prefix
TD002 Use Target Servers
> Fix for issues #158, #159 and Feature TD002

- lib/package/plugins/useTargetServers.js
- package.json
- test/specs/testuseTargetServers.js
TD002 was incorrectly reporting URL usage.
Added test cases.
> Fixed issue #161, TD002 incorrect report

- README.md
- cli.js
- externalPlugins/EX-PO007-NamingConventions.js
- lib/package/bundleLinter.js
- package.json
Test using:
```
node ./cli.js -x ./externalPlugins -f table.js -s test/fixtures/resources/sampleProxy/24Solver/apiproxy
```
will show EX-PO007 in output.
> Fix for issue #163 - external plugin support

- lib/package/plugins/checkConditionTruth.js
There is a small typing error in a message ("absuridty").
> Fix a typing mistake in 'logical absurdity' message

- lib/package/plugins/eslint.js
The eslint plugin now reads eslintrc files by default.
> eslint plugin now reads eslintrc files

- lib/package/plugins/checkBundleStructure.js
> allow template subdir in resources dir

- lib/package/plugins/checkBundleStructure.js
> support .yaml extension for openapi resources

- lib/package/plugins/emptyRouteRuleLast.js
> correct check of expression for PD003

- lib/package/plugins/checkFaultRuleCondition.js
Add line and column into the message.
> improve message for FR001

- lib/package/Endpoint.js
With this change, the messages on an endpoint get delivered in sorted fashion, first by line, then by column.
> sort messages on an endpoint by line, column

- lib/package/plugins/checkForEmptySteps.js
More nuance in ST001 "Empty Steps". It now checks for a missing Name element, as well as for a missing text value within the element.
> ST001 more nuance

- .gitignore
- README.md
- lib/package/plugins/checkStepStructure.js
- test/fixtures/resources/ST002-step-hygiene/apiproxy/ST002-step-hygiene.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/policies/AM-AddCORSHeaders.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/policies/AM-GenericError.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/ST002-step-hygiene/apiproxy/proxies/endpoint1.xml
check for
- no multiple Name elements
- no multiple Condition elements
- no stray child elements of Name or Condition
- no whitespace around policy/step name
- no elements aside from Name, Condition, FaultRules
> Step hygiene checks

- README.md
- lib/package/plugins/checkDefaultFaultRule.js
- test/fixtures/resources/default-fault-rules/apiproxy/default-fault-rules.xml
- test/fixtures/resources/default-fault-rules/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/default-fault-rules/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/default-fault-rules/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/default-fault-rules/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/default-fault-rules/apiproxy/targets/http-1.xml
checks for
- only child elements of Condition, AlwaysEnforce, and Step
- at most one AlwaysEnforce element
- at most one Condition element
> Default fault rule structure

- lib/package/bundleLinter.js
removed fix, values are not checked and will fail inelegantly tied to closes #120
> removed default destination for apiUpload

- lib/package/plugins/proxyNameAttr.js
- lib/package/plugins/targetNameAttr.js
Rule PD004 and TD003 now report as error.
> Fix Issue208

- .gitignore
- lib/package/plugins/policyNameConventions.js
- test/specs/testPolicyName.js
> Fix for #204

- lib/package/plugins/policyNameConventions.js
> Fix for #205

- README.md
- lib/package/plugins/po027-hmacPolicy.js
This policy checks the HMAC policy for various requirements on SecretKety, Algorithm.
> add plugin PO027 for HMAC policy usage

- lib/package/plugins/PO027-hmacPolicy.js
Fixes issue PO027 - error filename #216
> Renamed po027-hmacPolicy.js to proper convention

- lib/package/myUtil.js
getRuleId did not account for the windows platform file path representation.
> Fix for Windows platform, issue #221

- lib/package/plugins/PO007-policyNameConventions.js
- test/specs/quotaPrefix.js
- also add a new test specifically for the Quota policy
> update PO007 to allow single-char prefix

- test/specs/assignVariableHygiene.js
This commit does not change the function of the library. Only the tests.
> add tests for PO026, AssignVariable hygiene

- README.md
- cli.js
- lib/package/bundleLinter.js
- update cli.js to remove the options from the command-line tool
- update bundleLinter to remove the logic that conditionally uploads
- add the --list option to show the supported plugins and formatters
- update README to show the current cli options
> remove upload feature from cli

- test/specs/assignVariableHygiene.js
Update tests to be more thorough and correct.
This is a test-only PR. There is no change to the function of the plugin.
> improve PO026 test

- README.md
> move text in README to correct column in the table

- test/specs/assignVariableHygiene.js
> Revert "improve PO026 test"

- README.md
- lib/package/TruthTable.js
- lib/package/plugins/CC005-unterminatedStrings.js
- test/fixtures/resources/CC005-unterminated-string-in-condition/apiproxy/CC005-unterminated-string-in-conditional.xml
- test/fixtures/resources/CC005-unterminated-string-in-condition/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/CC005-unterminated-string-in-condition/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/CC005-unterminated-string-in-condition/apiproxy/proxies/endpoint1.xml
- test/specs/unterminatedStringInCondition.js
This change adds a new check, for unterminated strings in conditionals.
> Cc005 strings in conditional

- lib/package/plugins/PO026-assignVariableUsage.js
- test/fixtures/resources/PO026-assignVariable-in-RaiseFault/RF-Example-TextPlain-Invalid.xml
- test/fixtures/resources/PO026-assignVariable-in-RaiseFault/RF-Example-TextPlain-Valid.xml
- test/specs/assignVariableHygieneInRaiseFault.js
- new tests (success, fail) for same
> correctly handle AssignVariable within RaiseFault

- test/specs/assignVariableHygieneInRaiseFault.js
> accommodate changes in kurtkanaskie/Issue239

- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/BN001-propertiesset-demo1.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/policies/AM-Response-1.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/policies/JS-1.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/resources/properties/set1.properties
- test/specs/propertySetTest.js
Previously there was no test.
This change does not modify anything in the tool, it merely adds a test.
> add test with properties folder

- test/fixtures/resources/BN001-propertiesset-demo1/apiproxy/resources/frobjo/notused.txt
This is a test-only change.  No new function in the tool.
Fixup for the prior PR.
> added a file to the invalid folder; allow tests to pass

- lib/package/plugins/BN001-checkBundleStructure.js
- test/fixtures/resources/BN001-xsd-resources/apiproxy/BN001-xsd-resources.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/AM-Response-1.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/JS-1.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/MV-1.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/BN001-xsd-resources/apiproxy/resources/xsd/DomainData.xsd
- test/fixtures/resources/BN001-xsd-resources/apiproxy/resources/xsd/GlobalData.xsd
- test/fixtures/resources/BN001-xsd-resources/apiproxy/resources/xsd/ProductService.xsd
- test/fixtures/resources/BN001-xsd-resources/apiproxy/resources/xsd/set1.properties
- test/specs/xsdResourceTest.js
- add tests for same, including negative test
- this is for issue #258
> BN001 allow xsd folder under resources

- README.md
- lib/package/Endpoint.js
- lib/package/Step.js
- lib/package/bundleLinter.js
- lib/package/plugins/EP001-corsPolicyAttachment.js
- lib/package/plugins/PO007-policyNameConventions.js
- package.json
- test/fixtures/resources/EP001-cors-attachment/apiproxy/cors-demo.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/CORS-1.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/CORS-2.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/JS-RemoveCopiedHeaders.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/policies/RF-InvalidRequest.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/EP001-cors-attachment/apiproxy/targets/http-1.xml
- test/fixtures/resources/PO007-cors-policy/AM-CORS-1.xml
- test/fixtures/resources/PO007-cors-policy/CORS-1.xml
- test/fixtures/resources/PO007-messages/apiproxy/PO007-messages.xml
- test/fixtures/resources/PO007-messages/apiproxy/policies/AM-1.xml
- test/fixtures/resources/PO007-messages/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/PO007-messages/apiproxy/policies/Error-UnknownRequest.xml
- test/fixtures/resources/PO007-messages/apiproxy/policies/Setup.xml
- test/fixtures/resources/PO007-messages/apiproxy/proxies/endpoint1.xml
- test/specs/corsAttachment.js
- test/specs/corsPolicyName.js
- check naming conventions
- verify attachment in proxy endpoints
- verify non-attachment in target endpoints
> handle CORS policy

- lib/package/Bundle.js
- package-lock.json
- test/specs/testFaultRules.js
- also updated a test to verify that logic
> updated logic to get defaultfault rules count

- lib/package/plugins/EP001-corsPolicyAttachment.js
> EP001 handle edge case of no policies in bundle

- externalPlugins/EX-PO007-NamingConventions.js
- correctly handle handle missing entry for policy type
- use modern JS coding practices
> fixup example plugin

- lib/package/plugins/_extractVariablesCheck.js
- test/specs/PO003-ExtractJSON-ConditionCheck.js
> adjust regex to properly detect conditions in PO003

- LICENSE
- NOTICE
- README.md
Modified the license file to exclude the "instructions for applying the license". 
Also added a copyright notice file, and a link to same in README.
No change to function of the tool.
> Update license file, add reference in README

- README.md
- lib/package/RouteRule.js
- lib/package/plugins/PD001-missingTargets.js
- test/fixtures/resources/PD001-missing-target/apiproxy/PD001-missing-target.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/AM-CleanResponseHeaders.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/AM-InjectProxyVersionHeader.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/AM-Response-1.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/JS-1.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/MV-1.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/policies/RF-UnknownRequest.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/PD001-missing-target/apiproxy/targets/target2.xml
- test/specs/PD001-1.js
Implementation for new plugin, PD001, to check for missing targets. 
Also documentation in the README for same.
> add PD001 missing targets plugin

- lib/package/plugins/_extractVariablesCheck.js
- test/specs/PO004-ExtractXML-ConditionCheck.js
- use a more strict regex (check for word boundaries)
- emit the Condition and the line/column number that is flagged
No update to the README is necessary.
>  in PO004, use a more strict regex for Condition

- README.md
- cli.js
- lib/package/bundleLinter.js
> listing External plugin

- lib/package/plugins/EP002-misplacedElements.js
- test/fixtures/resources/EP002/apiproxy/targets/http-1.xml
- test/specs/EP002-elementPlacement.js
> Updated PR to address issue 320

- lib/package/plugins/EP002-misplacedElements.js
- test/fixtures/resources/EP002/apiproxy/targets/http-1.xml
- test/specs/EP002-elementPlacement.js
> Apigeelint fix for HealthMonitor configuration

- lib/package/plugins/EP002-misplacedElements.js
- test/fixtures/resources/EP002/apiproxy/proxies/proxy-endpoint-1.xml
- test/fixtures/resources/EP002/apiproxy/proxies/proxy-endpoint-2.xml
- test/specs/EP002-elementPlacement.js
> in EP002, allow URL under RouteRule

- lib/package/plugins/PO032-CORS-hygiene.js
- test/fixtures/resources/PO032/fail/CORS-Expose-Mixed.xml
- test/fixtures/resources/PO032/fail/messages.js
- test/fixtures/resources/PO032/pass/CORS-Expose-All.xml
As per docs, this is a valid configuration.
Added appropriate tests and all pass via` npm test`
> Issue #340 - <ExposeHeaders>*</ExposeHeaders> is OK

- lib/package/plugins/EP002-misplacedElements.js
- lib/package/plugins/PD005-unnecessaryVirtualHost.js
- test/specs/EP002-elementPlacement.js
small changes to check for Sharedflows in these plugins.
> Introduce Sharedflow awareness to EP002 and PD005

- package.json
very smol change to update the description field in the package.json
> update module description

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/Policy.js
- lib/package/Resource.js
- lib/package/myUtil.js
> normalize path formats to fully-qualified

- lib/package/Policy.js
- package-lock.json
- test/specs/EP002-elementPlacement.js
- test/specs/FR001-checkFaultRuleCondition.js
- test/specs/FR003.js
- test/specs/PO026-profile.js
- test/specs/TD002-edgemicro.js
- test/specs/TD002-edgemicroNot.js
Changes made for issue 353 require changes in tests that examine error messages.
> update tests to accommodate new error msg format

- lib/package/plugins/EP002-misplacedElements.js
> fix: "Misplaced 'Condition' element child of DefaultFaultRule"

- README.md
- lib/package/Policy.js
- lib/package/plugins/BN011-wellFormedXml.js
- package-lock.json
- package.json
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/linttest-1.xml
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/policies/AM-Clean-Request-Headers-From-Response.xml
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/BN011-well-formed-xml/apiproxy/proxies/endpoint1.xml
- test/specs/BN011-wellFormedXmlTest.js
This plugin checks XML for well-formedness.  
It requires a new parser, as xmldom/xmldom does not do this.  
This plugin addresses issue #357.
> add new plugin to check XML for well-formedness

- README.md
- cli.js
- lib/package/bundleLinter.js
- smarten up the treatment of the -w option
- introduce new --quiet command-line option
- also update README
This addresses issue #101 and also #165
> fix: allow writing to file or directory

- README.md
Add a section on the `--profile` option.
> docs: improve docs around apigeelint profile

- lib/package/plugins/TD004-targetSslInfo.js
- test/specs/TD004-sslInfo.js
The Enforce element is appropriate only for Apigee X / hybrid. The tests check for that.
The changes in code formatting and whitespace are due to auto-reformatting using prettier.io .
> feat(TD004): add new check for Enforce element in TD004

- build/ConditionParser.js
- lib/package/plugins/CC007-ConditionSyntax.js
- lib/peggy/Apigee-Condition.pegjs
- test/specs/CC007-Condition-Syntax-Test.js
- test/specs/ConditionParserTest.js
make peggy grammar a bit more flexible to handle unusual spacing in Condition elements.
> fix: handle unusual spacing in conditions

- lib/package/plugins/FL001-unconditionalFlows.js
- test/specs/FL001-unconditional-flows-and-routes.js
One of the error messages emitted by FL001 is misleading. This change corrects that. 
There's really just one line changing in the impl, and one in the test.  And some reformatting of whitespace, etc.
> fix: clarify FL001 error message with unconditional flow

- README.md
- lib/package/plugins/TD004-targetSslInfo.js
- lib/package/plugins/TD006-target-LoadBalancer-SslInfo.js
- lib/package/plugins/TD007-targetSslInfo-Truststore.js
- test/specs/TD006-target-LB-SslInfo.js
- test/specs/TD007-target-sslInfo-truststore.js
- TD006 SSLInfo when LoadBalancer is present
- TD007 SSLInfo should use TrustStore
> fix: refactor TD004 to extract two small checks into unique plugins

- lib/package/plugins/PD004-proxyNameAttr.js
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/flightdata.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-Clean-Response-Headers.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-PreparedQuery-1.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-PreparedQuery-2.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-PreparedQuery-3.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-PreparedQuery-4.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/AM-Query.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/EV-PathParams-4.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/JS-Convert-Response.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/proxies/endpoint2.xml
- test/fixtures/resources/PD004-ProxyEndpoint-name/apiproxy/targets/target-1.xml
- test/specs/PD004-proxyendpoint-name.js
no new features, no function change. This is a tests-only change.  Adding a test for the PD004 plugin.
> chore: add tests for PD004 plugin

- lib/package/plugins/TD003-targetNameAttr.js
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/flightdata.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-Clean-Response-Headers.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-PreparedQuery-1.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-PreparedQuery-2.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-PreparedQuery-3.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-PreparedQuery-4.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/AM-Query.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/EV-PathParams-4.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/JS-Convert-Response.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/proxies/endpoint1.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/targets/target-1.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/targets/target-2.xml
- test/fixtures/resources/TD003-TargetEndpoint-name/apiproxy/targets/target-3.xml
- test/specs/TD003-targetendpoint-name.js
no new feature or function. Just an added test for TD003.
> chore: add test for TD003 plugin

- lib/package/myUtil.js
- lib/package/plugins/policyMetaData.json
- package-lock.json
- package.json
- test/specs/testXmlNodeLabels.js
> fix Xmldom resolution

- lib/package/downloader.js
Fixes Issue #497 sorts numerically
> Update downloader.js fixes Issue #497

- README.md
> fix: minor typo in README

- lib/package/Bundle.js
- lib/package/Endpoint.js
- lib/package/Policy.js
- lib/package/Resource.js
- lib/package/apigeelintrc.js
- lib/package/bundleLinter.js
- lib/package/downloader.js
- lib/package/findFolders.js
- lib/package/lintUtil.js
- lib/package/plugins/BN011-wellFormedXml.js
- test/specs/EP002-test.js
- test/specs/FR001-checkFaultRuleCondition.js
- test/specs/FR003.js
- test/specs/TD002-edgemicroNot.js
- test/specs/testBundle.js
I noticed that when running apigeelint on Windows the BN011 plugin was throwing an error.  
This fixes that problem (aka #509).  Also, some of the tests did not run successfully on Windows. This change also fixes that.
> BN011 pathfix

- lib/package/Bundle.js
- package-lock.json
- package.json
- test/fixtures/resources/issue481/package-lock.json
@DinoChiesa - can you please review this PR. It removes the "decompress" node module that has dependencies being pulled that have vulnerabilities but this module is not really used
> fix for #511

- lib/package/Flow.js
> fix: correct use of uninitialized var in debug stmt #521

- lib/package/Bundle.js
- lib/package/Step.js
- test/fixtures/resources/step-get-sample-proxy/apiproxy/jsonpath-test-3.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/policies/AM-Clean-Request-Headers-From-Response.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/policies/AM-Example-Payload-Jsonpath.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/policies/AM-Inject-Proxy-Revision-Header.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/policies/AM-Response.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/policies/RF-Unknown-Request.xml
- test/fixtures/resources/step-get-sample-proxy/apiproxy/proxies/endpoint1.xml
- test/specs/get-policy-for-step.js
This addresses #525 .
No new feature to be documented _for the tool_, though this does expose new methods on the Step class.
> feat: get Bundle and Policy from step

- README.md
- lib/package/plugins/TD004-targetSslInfo-enabled-and-enforce.js
- test/specs/TD004-test-sslInfo.js
Small adjustment in the warning message to cite profile. 
Also a corresponding change in the README.
> fix: adjust message on TD004 to cite the profile when appropriate

- lib/package/plugins/PO035-quota-hygiene.js
- test/fixtures/resources/PO035/policies/fail/messages.js
- test/specs/PO035-test-bundles.js
- test/specs/PO035-test-policies.js
- and also capitalizes sentences.
- and fixes #539 by properly constructing the mocks in the test
> fix: modify messages on PO035 to mention profile when appropriate
